### PR TITLE
Use GH actions to build container image

### PR DESCRIPTION
**Pull request by hoerup**

### CODE REVIEW

**Review by mjjbell — APPROVED** [review]
:+1:

**Comment by iKlsR** [comment]
Any chance we could get an actual 'latest' image?

**Comment by hoerup** [comment]
> Any chance we could get an actual 'latest' image?

What do you mean ? It's right here

https://github.com/Project-OSRM/osrm-frontend/pkgs/container/osrm-frontend

**Comment by iKlsR** [comment]
Docker noob so fiddling around. I was following the instructions in the backend repo. That seems to grab https://hub.docker.com/r/osrm/osrm-frontend, same when I run the following `docker run -p 9966:9966 osrm/osrm-frontend`. Pulling the image from ghcr.io and targeting that with `docker run -p 9966:9966 ghcr.io/project-osrm/osrm-frontend:latest` works. So I guess the readme can be updated to account for that.

osrm

**Pull request merged**
